name: Cypress E2E Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch: # Allows manual trigger

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run Cypress tests (Mock)
        run: npm run test:run
        continue-on-error: true
      
      - name: Generate HTML Report
        if: always()
        run: node cypress/support/generate-report.js
      
      - name: Upload Cucumber HTML Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cucumber-html-report
          path: cypress/reports/cucumber-html/
          retention-days: 30
      
      - name: Upload Screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots/
          retention-days: 7
      
      - name: Upload Videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos/
          retention-days: 7
      
      - name: Upload JSON Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cucumber-json-report
          path: cypress/reports/cucumber-json/
          retention-days: 30